export {
  ALL_PRODUCTS,
  CREATED_PRODUCT,
  ONE_PRODUCT,
  GET_PRODUCT_UPDATE,
  SORT_PRODUCT_DEPARTMENT,
  SORT_PRODUCT_CATALOG,
  SORT_PRODUCT_SIMILAR,
  SEARCH_PRODUCTS,
  ONE_PRODUCT_QUERY,
  GET__MAXVIEWS__ALLPRODUCT,
  GET__NEW__ALLPRODUCT,
  GET__MAXDISCOUNT__ALLPRODUCT,
} from "./productRequest";
